# Site settings
title: Ihboras Data Science Portfolio
email: ihboras3@hotmail.com
url: https://Ihboras.github.io
description: "Hi there, this is my personal Data Science portfolio that I have created."
keywords: "your keywords, separated by commas"
skills: "Data Scientist"
meta_author: Ihboras

# Google webmaster tools
#google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ac0000 #9D0000
  primary-rgb: "196,0,0" #"235,0,0"
  secondary: 4a4a4a #DF032E
  secondary-dark: 313131 #AC0000

# Footer settings
#footer:
 # copyright: Dr. Henry Jekyll
 # location: Location
 # social: Around the Web
 # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
 #   url: http://bitbucket.org/jekyll
#  - title: github
 #   url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
